trigger:
  branches:
    include:
      - main
  

# defines the image to be used
jobs:
- job: Installation
  pool:
    vmImage: ubuntu-latest

  steps:

  - task: UserPythonVersion@0
    inputs:
      versionSpec: '3.12'
    displayName: 'Setting Python Version'

  - script: |
        pip install poetry
        poetry intall 
      displayName: 'Install app dependencies'
  