trigger:
  branches:
    include:
      - main
  

# defines the image to be used
jobs:
- job: Installation
  pool:
    vmImage: ubuntu-latest

  steps:

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.12'
    displayName: 'Setting Python Version'

  - script: |
      pip install poetry
      poetry install 
    displayName: 'Install app dependencies'
      


  - task: AzureCLI@2
    inputs: 
      azureSubscription: "mlops-connection"
      scriptType: 'bash'
      scriptLocaltion: 'inlineScript'
      inlineScript: 'python assimilate_azops/app.py'
      addSpntoEnvironment: true
    displayName: 'Run a one-line script'
  